src/objects/Project__c.object
<CustomObject>
    <description>Shadow object containing records loaded from an inbound integration with the external PMS. It is a child to Opportunities as the originating source.</description>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ProjectRef__c</fullName>
        <externalId>true</externalId>
        <label>ProjectRef</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Running</fullName>
                </value>
                <value>
                    <fullName>Billable</fullName>
                </value>
                <value>
                    <fullName>Billed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/BillingCalloutService.cls
public class BillingCalloutService {
    
    public static boolean isRecursive = false;
    
    public static void callBillingService(List<Id> projectIdList){  
        makeCalloutToBillingService(projectIdList);
    }
    
    @future (callout=true)    
    public static void makeCalloutToBillingService(List<Id> projectIdList){  
        isRecursive = true;
        Map<String,String> mpResult = new Map<String,String>();
        List<Project__c> projectList = [select id, ProjectRef__c, Opportunity__r.Amount, Status__c from Project__c where id in :projectIdList];
        for(Project__c project: projectList){
            BillingServiceProxy.Project pr = new BillingServiceProxy.Project();
                pr.username = ServiceCredentials__c.getValues('BillingServiceCredential').Username__c;
            pr.password = ServiceCredentials__c.getValues('BillingServiceCredential').Password__c;
            pr.projectid = project.projectRef__c;
            pr.billAmount = project.Opportunity__r.amount;
            try
            {
                BillingServiceProxy.InvoicesPortSoap11 invoice = new BillingServiceProxy.InvoicesPortSoap11();
                String status = invoice.billProject(pr);   
                mpResult.put(project.Id,status);
                project.Status__c = 'Billed';
                update project;
            }
            catch(CalloutException e){
                System.debug('Exception when making SOAP callout');	
            }
        }        
    }        
}